library("dplyr")
library(lubridate)
f <- read.table("household_power_consumption.txt",header = TRUE, sep = ";",stringsAsFactors = FALSE)
f <- mutate(f,Date = dmy(Date))
data <- filter(f, year(Date) == 2007, month(Date) == 02, day(Date) < 3)
data <- mutate(data, Global_active_power = as.numeric(Global_active_power))
hist(data$Global_active_power, col = "red",xlab = "Global Active Power (kiliwatts)", main = "Global Active Power")
dev.copy(png,file = "plot1.png")
dev.off()