library("dplyr")
library(lubridate)
f <- read.table("household_power_consumption.txt",header = TRUE, sep = ";",stringsAsFactors = FALSE)
f <- within(f, DT <- paste(Date, Time, sep = " "))
f <- mutate(f,Date = dmy(Date))
data <- filter(f, year(Date) == 2007, month(Date) == 02, day(Date) < 3)
data <- mutate(data, DT = dmy_hms(DT))
data <- mutate(data, Global_active_power = as.numeric(Global_active_power))
plot(data$DT, data$Global_active_power, type = "l",xlab = "", ylab = "Global Active Power (kilowatts)")
dev.copy(png,file = "plot2.png")
dev.off()
